### ISSUE TITLE
Newer Regions not supported. They require AWS Signature Version 4 for S3

### ISSUE THREAD

**Issue by olir** [tonyp13/DragonDisk#2]
Trying to connect to an S3 bucket in eu-central-1 fails with the following error: 

**_InvalidRequest
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256._**

The reason is that newer Regions require AWS Signature Version 4 for S3.

**Comment by tonyp13** [comment]
Yes, the next release will support the AWS V4 signature and Path style access. It is almost ready.

**Comment by olir** [comment]
superb!!!

**Comment by lukas-schulze** [comment]
Any news about the release date?

**Comment by tonyp13** [comment]
March, maybe end of March.

**Comment by irishman2020** [comment]
It's past march, any update?

**Comment by irishman2020** [comment]
Two months later, any news @tonyp13 ?

**Comment by danielfm123** [comment]
still waigint... needing this now!

**Comment by HagnMarkus** [comment]
forget this tool!!! it still does not support v4!

"It is almost ready."... for one and a half year!

**Comment by danielfm123** [comment]
Too bad, I was going to donate from my company...
Now I'm using winscp
